name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Grants write access to repository contents (e.g., pushing commits)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine Version
        id: semantic
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "(BREAKING CHANGE:|feat!:)"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}"
          search_commit_body: true

      - name: Update manifest.json version
        run: |
          VERSION="${{ steps.semantic.outputs.version }}"
          sed -i 's/"version": "[^"]*"/"version": "'"$VERSION"'"/' custom_components/blynclight/manifest.json
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add custom_components/blynclight/manifest.json
          git commit -m "chore: update version to $VERSION"
          git push

      - name: Create Tag
        run: |
          VERSION="${{ steps.semantic.outputs.version }}"
          git tag "$VERSION"
          git push origin "$VERSION"

      - name: Generate Changelog
        id: changelog
        uses: BobAnkh/auto-generate-changelog@v1.2.5
        with:
          REPO_NAME: '${{ github.repository }}'
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PATH: 'CHANGELOG.md'
          COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
          TYPE: 'feat:New Features,fix:Bug Fixes,docs:Documentation,refactor:Refactoring,perf:Performance Improvements'

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.semantic.outputs.version }}
          release_name: v${{ steps.semantic.outputs.version }}
          body: |
            ## What's Changed
            
            ${{ steps.changelog.outputs.changelog }}
            
            ## Installation & Update Notes
            - After updating, restart Home Assistant
            - No configuration changes required
          draft: false
          prerelease: false
